config/routes.rb
Brewlog::Application.routes.draw do
  resources :hops
  resources :fermentables
  resources :yeasts

  resources :styles

  devise_for :users, controllers: { registrations: :registrations }

  root to: 'dashboard#index'
end

app/models/hop.rb
# == Schema Information
#
# Table name: hops
#
#  id            :integer          not null, primary key
#  name          :string(255)
#  origin        :string(255)
#  alpha         :decimal(, )
#  beta          :decimal(, )
#  description   :string(255)
#  form          :string(255)
#  hsi           :decimal(, )
#  humulone      :decimal(, )
#  cohumulone    :decimal(, )
#  adhumulone    :decimal(, )
#  lupulone      :decimal(, )
#  colupulone    :decimal(, )
#  adlupulone    :decimal(, )
#  humulene      :decimal(, )
#  myrcene       :decimal(, )
#  caryophyllene :decimal(, )
#  farnese       :decimal(, )
#  notes         :text
#  user_id       :integer
#  master        :boolean          default(FALSE)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Hop < ActiveRecord::Base

  include Masterable

  FORMS        = %w(Pellet Whole)
  DESCRIPTIONS = %w(Both Bittering Aroma)

  belongs_to :user

  validates_presence_of :name, :alpha, :beta
  validates_uniqueness_of :name, scope: :user_id

  validates_inclusion_of :description, in: DESCRIPTIONS
  validates_inclusion_of :form,        in: FORMS

  validates_numericality_of :alpha, :beta, :hsi, :humulone, :cohumulone,
    :adhumulone, :lupulone, :colupulone, :adlupulone, :humulene, :myrcene,
    :caryophyllene, :farnese, allow_nil: true

  validates_presence_of :user, unless: :master?

  def self.countries
    Hop.select("DISTINCT(origin)").where("origin IS NOT NULL").collect { |h| h.origin }.sort
  end
end

app/controllers/hops_controller.rb
class HopsController < ApplicationController

  def index
    @search = current_user.hops.search(params[:q])
    @hops   = @search.result(distinct: true)
  end

  def new
    @hop = current_user.hops.build
  end

  def create
    @hop = current_user.hops.build(hop_params)

    if @hop.save
      flash[:notice] = "#{@hop.name} was successfully created."
      redirect_to action: :index
    else
      render action: "new"
    end
  end

  def edit
    @hop = current_user.hops.find(params[:id])
  end

  def update
    @hop = current_user.hops.find(params[:id])

    if @hop.update_attributes(hop_params)
      flash[:notice] = "#{@hop.name} was successfully updated."
      redirect_to action: :index
    else
      render action: "edit"
    end
  end

  def destroy
    @hop = current_user.hops.find(params[:id])
    flash[:notice] = "#{@hop.name} was deleted."
    @hop.destroy
    redirect_to hops_path
  end

  private

  def hop_params
    params.require(:hop).permit(
      :name, :origin, :alpha, :beta, :description,
      :form, :hsi, :humulone, :cohumulone, :adhumulone,
      :lupulone, :colupulone, :adlupulone,
      :humulene, :myrcene, :caryophyllene, :farnese,
      :notes
    )
  end

end

app/views/hops/_form.html.erb
<%= form_for @hop, builder: BootstrapFormBuilder do |f| %>
  <div class="row-fluid">
    <div class="span3">
      <fieldset>
        <legend>General</legend>
        <div class="row-fluid">
          <%= f.text_field :name, class: "span11" %>
          <%= f.country_code_select :origin, [], {}, { class: "span11" } %>
        </div>
        <div class="row-fluid">
          <div class="span6">
            <%= f.text_field :alpha, class: "span6", append: "%" %>
            <%= f.text_field :beta, class: "span6", append: "%" %>
            <%= f.text_field :hsi, class: "span6", append: "%" %>
          </div>

          <div class="span6">
            <%= f.select :description, Hop::DESCRIPTIONS, {}, { class: "span8" } %>
            <%= f.select :form, Hop::FORMS, {}, { class: "span8" } %>
          </div>
        </div>

        <div class="row-fluid">
          <div class="span12">
            <%= f.text_area :notes, class: "input-block-level", rows: 10 %>
          </div>
        </div>
      </fieldset>
    </div>
    <div class="span3 offset1">
      <fieldset>
        <legend>Alpha acids</legend>

        <div class="row-fluid">
          <div class="span6">
            <%= f.text_field :humulone, class: "span6", append: "%" %>
            <%= f.text_field :cohumulone, class: "span6", append: "%" %>
          </div>
          <div class="span6">
            <%= f.text_field :adhumulone, class: "span6", append: "%" %>
          </div>
        </div>
      </fieldset>

      <fieldset>
        <legend>Beta acids</legend>

        <div class="row-fluid">
          <div class="span6">
            <%= f.text_field :lupulone, class: "span6", append: "%" %>
            <%= f.text_field :colupulone, class: "span6", append: "%" %>
          </div>
          <div class="span6">
            <%= f.text_field :adlupulone, class: "span6", append: "%" %>
          </div>
        </div>
      </fieldset>
    </div>
    <div class="span3 offset1">
      <fieldset>
        <legend>Essential oils</legend>

        <div class="row-fluid">
          <div class="span6">
            <%= f.text_field :humulene, class: "span6", append: "%" %>
            <%= f.text_field :myrcene, class: "span6", append: "%" %>
          </div>
          <div class="span6">
            <%= f.text_field :caryophyllene, class: "span6", append: "%" %>
            <%= f.text_field :farnese, class: "span6", append: "%" %>
          </div>
        </div>
      </fieldset>
    </div>
  </div>
  <div class="form-actions">
    <% unless @hop.new_record? %>
      <a href="<%= hop_path(@hop) %>" class="btn btn-danger" data-confirm="Are you sure?" data-method="delete" rel="nofollow"><i class="icon-trash"></i> Delete</a>
    <% end %>
    <button type="submit" class="btn btn-primary"><i class="icon-save"></i> Save</button>
  </div>
<% end %>

app/views/hops/edit.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li><a href="<%= fermentables_path %>">Fermentables</a> <span class="divider">/</span></li>
  <li class="active">Edit a Fermentable</li>
</ul>
<%= render partial: "form", object: @hop %>

app/views/hops/index.html.erb
<div class="row-fluid">
  <div class="span12">
    <div class="navbar">
      <div class="navbar-inner">
        <a class="brand" href="<%= hops_path %>">Hops</a>
        <a class="btn btn-success pull-right" href="/hops/new"><i class="icon-plus"></i> Create a Hop</a>
      </div>
    </div>
  </div>
</div>
<div class="row-fluid">
  <div class="span3 well well-small entity-sidebar">
    <%= search_form_for @search do |f| %>
      <label>Name:</label>
      <div class="input-append entity-sidebar-search">
        <%= f.text_field :name_cont, class: "input-block-level", placeholder: "Search" %>
        <span class="add-on"><i class="icon-search"></i></span>
      </div>

      <label>Type:</label>
      <%= f.select :description_eq, Hop::DESCRIPTIONS, {include_blank: true}, {class: "input-block-level"} %>

      <label>Origin:</label>
      <%= f.select :origin_eq, Hop.countries, {include_blank: true}, {class: "input-block-level"} %>

      <label>Alpha:</label>
      <div class="controls controls-row">
        <label class="span4 control-label">between</label>
        <%= f.select :alpha_gteq, 20.times.collect { |t| [t, t.to_f] }, {include_blank: true}, {class: "span3"} %>
        <label class="span2 control-label">and</label>
        <%= f.select :alpha_lteq, 20.times.collect { |t| [t, t.to_f] }, {include_blank: true}, {class: "span3"} %>
      </div>

      <label class="hidden-phone">Beta:</label>
      <div class="controls controls-row hidden-phone">
        <label class="span4 control-label">between</label>
        <%= f.select :beta_gteq, 20.times.collect { |t| [t, t.to_f] }, {include_blank: true}, {class: "span3"} %>
        <label class="span2 control-label">and</label>
        <%= f.select :beta_lteq, 20.times.collect { |t| [t, t.to_f] }, {include_blank: true}, {class: "span3"} %>
      </div>

      <label class="hidden-phone">Form:</label>
      <%= f.select :form_eq, Hop::FORMS, {include_blank: true}, {class: "input-block-level hidden-phone"} %>

      <div class="form-actions">
        <button type="submit" class="btn btn-primary pull-right"><i class="icon-filter"></i> Filter</button>
      </div>
    <% end %>
  </div>
  <div class="span9 entity-content">
    <table class="table table-bordered table-striped">
      <tr>
        <th><%= sort_link @search, :name, "Name" %></th>
        <th><%= sort_link @search, :description, "Type" %></th>
        <th><%= sort_link @search, :origin, "Origin" %></th>
        <th><%= sort_link @search, :alpha, "Alpha" %></th>
        <th class="hidden-phone"><%= sort_link @search, :beta, "Beta" %></th>
        <th class="hidden-phone"><%= sort_link @search, :form, "Form" %></th>
      </tr>
      <% @hops.each do |hop| %>
        <tr>
          <td><%= link_to hop.name, edit_hop_path(hop) %></td>
          <td><%= hop.description %></td>
          <td><%= hop.origin %></td>
          <td><%= number_with_precision(hop.alpha, precision: 2) %>%</td>
          <td class="hidden-phone"><%= number_with_precision(hop.beta, precision: 2) %>%</td>
          <td class="hidden-phone"><%= hop.form %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/hops/new.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li><a href="<%= hops_path %>">Hops</a> <span class="divider">/</span></li>
  <li class="active">Create a Hop</li>
</ul>
<%= render partial: "form", object: @hop %>