config/routes.rb
Brewlog::Application.routes.draw do
  resources :hops
  resources :fermentables
  resources :yeasts

  resources :styles

  devise_for :users, controllers: { registrations: :registrations }

  root to: 'dashboard#index'
end

app/controllers/fermentables_controller.rb
class FermentablesController < ApplicationController

  def index
    @search       = current_user.fermentables.search(params[:q])
    @fermentables = @search.result(distinct: true)
  end

  def new
    @fermentable = current_user.fermentables.build
  end

  def create
    @fermentable = current_user.fermentables.build(fermentable_params)

    if @fermentable.save
      flash[:notice] = "#{@fermentable.name} was successfully created."
      redirect_to action: :index
    else
      render action: "new"
    end
  end

  def edit
    @fermentable = current_user.fermentables.find(params[:id])
  end

  def update
    @fermentable = current_user.fermentables.find(params[:id])

    if @fermentable.update_attributes(fermentable_params)
      flash[:notice] = "#{@fermentable.name} was successfully updated."
      redirect_to action: :index
    else
      render action: "edit"
    end
  end

  def destroy
    @fermentable = current_user.fermentables.find(params[:id])
    flash[:notice] = "#{@fermentable.name} was deleted."
    @fermentable.destroy
    redirect_to fermentables_path
  end

  private

  def fermentable_params
    params.require(:fermentable).permit(
      :name, :origin, :supplier, :description, :max_in_batch,
      :potential, :yield, :coarse_fine_difference, :moisture,
      :diastatic_power, :protein, :ibu, :color, :recommended_mash,
      :add_after_boil, :notes
    )
  end

end

app/views/fermentables/_form.html.erb
<%= form_for @fermentable, builder: BootstrapFormBuilder do |f| %>
  <div class="row-fluid">
    <div class="span3">
      <fieldset>
        <legend>General</legend>
        <div class="row-fluid">
          <%= f.text_field :name, class: "span11" %>
          <%= f.text_field :supplier, class: "span11" %>
          <%= f.select :description, Fermentable::DESCRIPTIONS, {}, { class: "span11" } %>
          <%= f.country_code_select :origin, [], {}, { class: "span11" } %>
        </div>

        <div class="row-fluid">
          <div class="span12">
            <%= f.text_area :notes, class: "input-block-level", rows: 10 %>
          </div>
        </div>
      </fieldset>
    </div>
    <div class="span3 offset1">
      <fieldset>
        <legend>Properties</legend>
        <div class="row-fluid">
          <div class="span6">
            <%= f.text_field :max_in_batch, class: "span6", append: "%" %>
            <%= f.text_field :diastatic_power, class: "span6 hidable grain", append: "°L" %>
            <%= f.text_field :protein, class: "span6 hidable grain", append: "%" %>
            <%= f.text_field :ibu, label: "IBU", class: "span6 hidable extract", append: "gal/lb" %>
          </div>

          <div class="span6">
            <%= f.text_field :color, class: "span6", append: "SRM" %>
            <%= f.text_field :moisture, class: "span6 hidable grain", append: "%" %>
          </div>
        </div>

        <div class="row-fluid">
          <div class="span12">
            <%= f.check_box :recommended_mash, class: "span12 hidable grain" %>
            <%= f.check_box :add_after_boil, class: "span12" %>
          </div>
        </div>
      </fieldset>
    </div>
    <div class="span3 offset1">
      <fieldset>
        <legend>Yield</legend>
        <div class="row-fluid">
          <div class="span6">
            <%= f.text_field :potential, class: "span6", append: "SG" %>
            <%= f.text_field :coarse_fine_difference, label: "Coarse/Fine difference", class: "span6 hidable grain", append: "%" %>
          </div>

          <div class="span6">
            <%= f.text_field :yield, class: "span6", append: "%" %>
          </div>
        </div>
      </fieldset>
    </div>
  </div>
  <div class="form-actions">
    <% unless @fermentable.new_record? %>
      <a href="<%= fermentable_path(@fermentable) %>" class="btn btn-danger" data-confirm="Are you sure?" data-method="delete" rel="nofollow"><i class="icon-trash"></i> Delete</a>
    <% end %>
    <button type="submit" class="btn btn-primary"><i class="icon-save"></i> Save</button>
  </div>
<% end %>

app/views/fermentables/edit.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li><a href="<%= fermentables_path %>">Fermentables</a> <span class="divider">/</span></li>
  <li class="active">Edit a Fermentable</li>
</ul>
<%= render partial: "form", object: @fermentable %>

app/views/fermentables/index.html.erb
<div class="row-fluid">
  <div class="span12">
    <div class="navbar">
      <div class="navbar-inner">
        <a class="brand" href="<%= fermentables_path %>">Fermentables</a>
        <a class="btn btn-success pull-right" href="/fermentables/new"><i class="icon-plus"></i> Create a Fermentable</a>
      </div>
    </div>
  </div>
</div>
<div class="row-fluid">
  <div class="span3 well well-small entity-sidebar">
    <%= search_form_for @search do |f| %>
      <label>Name:</label>
      <div class="input-append entity-sidebar-search">
        <%= f.text_field :name_cont, class: "input-block-level", placeholder: "Search" %>
        <span class="add-on"><i class="icon-search"></i></span>
      </div>

      <label>Type:</label>
      <%= f.select :description_eq, Fermentable::DESCRIPTIONS, {include_blank: true}, {class: "input-block-level"} %>

      <label>Origin:</label>
      <%= f.select :origin_eq, Fermentable.countries, {include_blank: true}, {class: "input-block-level"} %>

      <label>Supplier:</label>
      <%= f.select :supplier_eq, Fermentable.suppliers, {include_blank: true}, {class: "input-block-level"} %>

      <div class="form-actions">
        <button type="submit" class="btn btn-primary pull-right"><i class="icon-filter"></i> Filter</button>
      </div>
    <% end %>
  </div>
  <div class="span9 entity-content">
    <table class="table table-bordered table-striped">
      <tr>
        <th><%= sort_link @search, :name, "Name" %></th>
        <th><%= sort_link @search, :description, "Type" %></th>
        <th><%= sort_link @search, :origin, "Origin" %></th>
        <th><%= sort_link @search, :supplier, "Supplier" %></th>
      </tr>
      <% @fermentables.each do |fermentable| %>
        <tr>
          <td><%= link_to fermentable.name, edit_fermentable_path(fermentable) %></td>
          <td><%= fermentable.description %></td>
          <td><%= fermentable.origin %></td>
          <td><%= fermentable.supplier%></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/fermentables/new.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li><a href="<%= fermentables_path %>">Fermentables</a> <span class="divider">/</span></li>
  <li class="active">Create a Fermentable</li>
</ul>
<%= render partial: "form", object: @fermentable %>