config/routes.rb
Brewlog::Application.routes.draw do
  resources :hops
  resources :fermentables
  resources :yeasts

  resources :styles

  devise_for :users, controllers: { registrations: :registrations }

  root to: 'dashboard#index'
end

app/models/style.rb
# == Schema Information
#
# Table name: styles
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  category        :string(255)
#  category_number :string(255)
#  style_letter    :string(255)
#  style_guide     :string(255)
#  description     :string(255)
#  og_min          :decimal(, )
#  og_max          :decimal(, )
#  fg_min          :decimal(, )
#  fg_max          :decimal(, )
#  ibu_min         :decimal(, )
#  ibu_max         :decimal(, )
#  color_min       :decimal(, )
#  color_max       :decimal(, )
#  carb_min        :decimal(, )
#  carb_max        :decimal(, )
#  abv_min         :decimal(, )
#  abv_max         :decimal(, )
#  notes           :text
#  profile         :text
#  ingredients     :text
#  examples        :text
#  master          :boolean
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Style < ActiveRecord::Base

  include Masterable

  DESCRIPTIONS = %w(Lager Ale Mead Wheat Mixed Cider)

  belongs_to :user

  validates_presence_of :abv_max, :abv_min, :carb_max, :carb_min,
    :color_max, :color_min, :fg_max, :fg_min, :ibu_max, :ibu_min,
    :name, :og_max, :og_min

  validates_inclusion_of :description,  in: DESCRIPTIONS

  validates_presence_of :user, unless: :master?
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController

  def index
    @search = current_user.styles.search(params[:q])
    @styles = @search.result(distinct: true)
  end

  def new
    @style = current_user.styles.build
  end

  def create
    @style = current_user.styles.build(style_params)

    if @style.save
      flash[:notice] = "#{@style.name} was successfully created."
      redirect_to action: :index
    else
      render action: "new"
    end
  end

  def edit
    @style = current_user.styles.find(params[:id])
  end

  def update
    @style = current_user.styles.find(params[:id])

    if @style.update_attributes(style_params)
      flash[:notice] = "#{@style.name} was successfully updated."
      redirect_to action: :index
    else
      render action: "edit"
    end
  end

  def destroy
    @style = current_user.styles.find(params[:id])
    flash[:notice] = "#{@style.name} was deleted."
    @style.destroy
    redirect_to styles_path
  end

  private

  def style_params
    params.require(:style).permit(
      :abv_max, :abv_min, :carb_max, :carb_min, :category, 
      :category_number, :color_max, :color_min, :description, 
      :examples, :fg_max, :fg_min, :ibu_max, :ibu_min, :ingredients, 
      :name, :notes, :og_max, :og_min, :profile, :style_guide, 
      :style_letter
    )
  end
end

app/views/styles/_form.html.erb
<%= form_for @style, builder: BootstrapFormBuilder do |f| %>
  <div class="row-fluid">
    <div class="span3">
      <fieldset>
        <legend>General</legend>
        <div class="row-fluid">
          <%= f.text_field :name, class: "span11" %>
          <%= f.text_field :category, class: "span11" %>
          <%= f.text_field :category_number, class: "span11" %>
          <%= f.text_field :style_letter, class: "span11" %>
          <%= f.text_field :style_guide, class: "span11" %>
        </div>
        <div class="row-fluid">
        </div>
      </fieldset>
    </div>
  </div>
  <div class="form-actions">
    <% unless @style.new_record? %>
      <a href="<%= style_path(@style) %>" class="btn btn-danger" data-confirm="Are you sure?" data-method="delete" rel="nofollow"><i class="icon-trash"></i> Delete</a>
    <% end %>
    <button type="submit" class="btn btn-primary"><i class="icon-save"></i> Save</button>
  </div>
<% end %>

app/views/styles/edit.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li><a href="<%= styles_path %>">Style</a> <span class="divider">/</span></li>
  <li class="active">Edit a Style</li>
</ul>
<%= render partial: "form", object: @style %>

app/views/styles/index.html.erb
<div class="row-fluid">
  <div class="span12">
    <div class="navbar">
      <div class="navbar-inner">
        <a class="brand" href="<%= styles_path %>">Styles</a>
        <a class="btn btn-success pull-right" href="/styles/new"><i class="icon-plus"></i> Create a Style</a>
      </div>
    </div>
  </div>
</div>
<div class="row-fluid">
  <div class="span3 well well-small entity-sidebar">
    <%= search_form_for @search do |f| %>
      <label>Name:</label>
      <div class="input-append entity-sidebar-search">
        <%= f.text_field :name_cont, class: "input-block-level", placeholder: "Search" %>
        <span class="add-on"><i class="icon-search"></i></span>
      </div>

      <label>Type:</label>
      <%= f.select :description_eq, Style::DESCRIPTIONS, {include_blank: true}, {class: "input-block-level"} %>

      <div class="form-actions">
        <button type="submit" class="btn btn-primary pull-right"><i class="icon-filter"></i> Filter</button>
      </div>
    <% end %>
  </div>
  <div class="span9 entity-content">
    <table class="table table-bordered table-striped">
      <tr>
        <th><%= sort_link @search, :name, "Name" %></th>
        <th><%= sort_link @search, :description, "Type" %></th>
      </tr>
      <% @styles.each do |style| %>
        <tr>
          <td><%= link_to style.name, edit_style_path(style) %></td>
          <td><%= style.description %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/styles/new.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li><a href="<%= styles_path %>">Styles</a> <span class="divider">/</span></li>
  <li class="active">Create a Style</li>
</ul>
<%= render partial: "form", object: @style %>