config/routes.rb
Brewlog::Application.routes.draw do
  resources :hops
  resources :fermentables
  resources :yeasts

  resources :styles

  devise_for :users, controllers: { registrations: :registrations }

  root to: 'dashboard#index'
end

app/models/yeast.rb
# == Schema Information
#
# Table name: yeasts
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  laboratory      :string(255)
#  description     :string(255)
#  form            :string(255)
#  product_id      :string(255)
#  min_temperature :decimal(, )
#  max_temperature :decimal(, )
#  min_attenuation :decimal(, )
#  max_attenuation :decimal(, )
#  flocculation    :string(255)
#  master          :boolean          default(FALSE)
#  notes           :text
#  user_id         :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Yeast < ActiveRecord::Base

  include Masterable

  FORMS = %w(Liquid Dry Slant Culture)
  DESCRIPTIONS = %w(Ale Lager Wheat Wine Champagne)
  FLOCCULATIONS = ['Low', 'Medium', 'High', 'Very High']

  belongs_to :user

  validates_presence_of :name, :min_attenuation, :max_attenuation

  validates_inclusion_of :description,  in: DESCRIPTIONS
  validates_inclusion_of :form,         in: FORMS
  validates_inclusion_of :flocculation, in: FLOCCULATIONS 

  validates_presence_of :user, unless: :master?

  def self.laboratories
    Yeast.select("DISTINCT(laboratory)").where("laboratory IS NOT NULL").collect { |f| f.laboratory }.sort
  end
end

app/controllers/yeasts_controller.rb
class YeastsController < ApplicationController

  def index
    @search = current_user.yeasts.search(params[:q])
    @yeasts   = @search.result(distinct: true)
  end

  def new
    @yeast = current_user.yeasts.build
  end

  def create
    @yeast = current_user.yeasts.build(yeast_params)

    if @yeast.save
      flash[:notice] = "#{@yeast.name} was successfully created."
      redirect_to action: :index
    else
      render action: "new"
    end
  end

  def edit
    @yeast = current_user.yeasts.find(params[:id])
  end

  def update
    @yeast = current_user.yeasts.find(params[:id])

    if @yeasts.update_attributes(yeast_params)
      flash[:notice] = "#{@yeast.name} was successfully updated."
      redirect_to action: :index
    else
      render action: "edit"
    end
  end

  def destroy
    @yeast = current_user.yeasts.find(params[:id])
    flash[:notice] = "#{@yeast.name} was deleted."
    @yeast.destroy
    redirect_to yeasts_path
  end

  private

  def yeast_params
    params.require(:yeast).permit(
      :name, :laboratory, :description, :form, :product_id,
      :min_temperature, :max_temperature, :min_attenuation,
      :max_attenuation, :flocculation, :notes
    )
  end
end

app/views/yeasts/_form.html.erb
<%= form_for @yeast, builder: BootstrapFormBuilder do |f| %>
  <div class="row-fluid">
    <div class="span3">
      <fieldset>
        <legend>General</legend>
        <div class="row-fluid">
          <%= f.text_field :name, class: "span11" %>
          <%= f.text_field :laboratory, class: "span11" %>
          <%= f.text_field :product_id, class: "span11" %>
        </div>

        <div class="row-fluid">
          <div class="span12">
            <%= f.text_area :notes, class: "input-block-level", rows: 10 %>
          </div>
        </div>
      </fieldset>
    </div>
    <div class="span4 offset1">
      <fieldset>
        <legend>Properties</legend>
        <div class="row-fluid">
          <div class="span6">
            <%= f.text_field :min_attenuation, label: "Min Attenuation", class: "span6", append: "%" %>
            <%= f.text_field :max_attenuation, label: "Max Attenuation", class: "span6", append: "%" %>
            <%= f.select :description, Yeast::DESCRIPTIONS, {}, {class: "span8"} %>
            <%= f.select :flocculation, Yeast::FLOCCULATIONS, {}, {class: "span8"} %>
            <%= f.select :form, Yeast::FORMS, {}, { class: "span8" } %>
          </div>
          <div class="span6">
            <%= f.text_field :min_temperature, label: "Min Temperature", class: "span6", append: "F" %>
            <%= f.text_field :max_temperature, label: "Max Temperature", class: "span6", append: "F" %>
          </div>
        </div>
      </fieldset>
    </div>
  </div>
  <div class="form-actions">
    <% unless @yeast.new_record? %>
      <a href="<%= yeast_path(@yeast) %>" class="btn btn-danger" data-confirm="Are you sure?" data-method="delete" rel="nofollow"><i class="icon-trash"></i> Delete</a>
    <% end %>
    <button type="submit" class="btn btn-primary"><i class="icon-save"></i> Save</button>
  </div>
<% end %>

app/views/yeasts/edit.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li><a href="<%= yeasts_path %>">Yeast</a> <span class="divider">/</span></li>
  <li class="active">Edit a Yeast</li>
</ul>
<%= render partial: "form", object: @yeast %>

app/views/yeasts/index.html.erb
<div class="row-fluid">
  <div class="span12">
    <div class="navbar">
      <div class="navbar-inner">
        <a class="brand" href="<%= yeasts_path %>">Yeasts</a>
        <a class="btn btn-success pull-right" href="/yeasts/new"><i class="icon-plus"></i> Create a Yeast</a>
      </div>
    </div>
  </div>
</div>
<div class="row-fluid">
  <div class="span3 well well-small entity-sidebar">
    <%= search_form_for @search do |f| %>
      <label>Name:</label>
      <div class="input-append entity-sidebar-search">
        <%= f.text_field :name_cont, class: "input-block-level", placeholder: "Search" %>
        <span class="add-on"><i class="icon-search"></i></span>
      </div>

      <label>Product ID:</label>
      <div class="input-append entity-sidebar-search">
        <%= f.text_field :product_id_cont, class: "input-block-level", placeholder: "Search" %>
        <span class="add-on"><i class="icon-search"></i></span>
      </div>

      <label>Laboratory:</label>
      <%= f.select :laboratory_eq, Yeast.laboratories, {include_blank: true}, {class: "input-block-level"} %>

      <label>Type:</label>
      <%= f.select :description_eq, Yeast::DESCRIPTIONS, {include_blank: true}, {class: "input-block-level"} %>

      <label>Form:</label>
      <%= f.select :form_eq, Yeast::FORMS, {include_blank: true}, {class: "input-block-level"} %>

      <div class="form-actions">
        <button type="submit" class="btn btn-primary pull-right"><i class="icon-filter"></i> Filter</button>
      </div>
    <% end %>
  </div>
  <div class="span9 entity-content">
    <table class="table table-bordered table-striped">
      <tr>
        <th><%= sort_link @search, :name, "Name" %></th>
        <th><%= sort_link @search, :laboratory, "Laboratory" %></th>
        <th><%= sort_link @search, :product_id, "Product ID" %></th>
        <th><%= sort_link @search, :description, "Type" %></th>
        <th><%= sort_link @search, :form, "Form" %></th>
      </tr>
      <% @yeasts.each do |yeast| %>
        <tr>
          <td><%= link_to yeast.name, edit_yeast_path(yeast) %></td>
          <td><%= yeast.laboratory %></td>
          <td><%= yeast.product_id %></td>
          <td><%= yeast.description %></td>
          <td><%= yeast.form %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/yeasts/new.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li><a href="<%= yeasts_path %>">Yeasts</a> <span class="divider">/</span></li>
  <li class="active">Create a Yeast</li>
</ul>
<%= render partial: "form", object: @yeast %>